name: deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        spring-boot-version: [3.0.6]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: âœ… ì²´í¬ì•„ì›ƒ source code.
        uses: actions/checkout@v3

      - name: ğŸ“¦ ì½”ë“œë¥¼ ì••ì¶•
        run: zip -r memory_of_msa.zip ./api-gateway ./eureka_server ./springKafka ./user-service ./scripts ./appspec.yml ./.env

      - name: ğŸŒ AWSì— ì ‘ì†
        uses: aws-actions/configure-aws-credentials@v1
        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: ap-northeast-2

#      - name: ğŸ¦– S3ì— ì••ì¶•ëœ ì„œë²„ ì½”ë“œë¥¼ ì—…ë¡œë“œ
#        run: aws s3 cp --region ap-northeast-2 ./partners.zip s3://partners-github-test/deploy/
#
#      - name: ğŸš€ AWS codeDeployë¡œ ë°°í¬ë¥¼ ì‹œì‘
#        run: aws deploy create-deployment
#          --application-name partners-erp-code-deploy-test
#          --deployment-config-name CodeDeployDefault.OneAtATime
#          --deployment-group-name partners-erp-deploy-test-group
#          --s3-location bucket=partners-github-test,bundleType=zip,key=deploy/partners.zip